name: Setting up server

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  Node-server:
    name: "Running a node server using ansible playbook"
    runs-on: ubuntu-latest

    steps:
      - name: "Check Github repo"
        uses: actions/checkout@v3

      # - name: "Setting up SSH"
      #   uses: appleboy/ssh-action@v1
      #   with:
      #     host: ${{secrets.SSH_HOST}}
      #     username: ec2-user
      #     key: ${{secrets.SSH_KEY}}
      #     script: |
      #       mkdir -p ~/.ssh
      #       echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
      #       chmod 600 ~/.ssh/id_rsa
      #       ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: "Install ansible"
        run: sudo apt-get update -y && sudo apt-get install -y ansible

      - name: "Setup SSH for Ansible"
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: "Run the playbook"
        run: ansible-playbook -i hosts.ini node_service.yaml --tags app
